# Generated by Django 3.2.6 on 2021-08-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerTry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SerializerTry.person')),
                ('roll_no', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=1)),
                ('cgpa', models.FloatField()),
                ('semester', models.PositiveSmallIntegerField()),
            ],
            bases=('SerializerTry.person',),
        ),
    ]
