# Generated by Django 3.2.6 on 2021-09-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerTry', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SerializerTry.person')),
                ('salary', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
            ],
            bases=('SerializerTry.person',),
        ),
    ]
