# Generated by Django 3.2.6 on 2021-09-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SerializerTry', '0003_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SerializerTry.person')),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('specility', models.CharField(choices=[('Heart Surgen', 'Heart Surgen'), ('Brain Surgen', 'Brain Surgen')], max_length=15)),
            ],
            bases=('SerializerTry.person',),
        ),
    ]
